# Generated by Django 4.1.2 on 2022-11-08 18:03

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.upload_to),
        ),
    ]
