# Generated by Django 4.1.3 on 2022-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_project_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
