# Generated by Django 4.1.2 on 2022-10-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
    ]
