# Generated by Django 4.1.2 on 2022-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogmodel_file_upload_remove_blogmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='articles',
            field=models.TextField(default='no thoughts'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.CharField(default='no tags', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(default='no titles', max_length=50),
        ),
    ]
