# Generated by Django 4.1.2 on 2022-11-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmodel_articles_blogmodel_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='uploads/file_upload'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/image'),
        ),
    ]
