# Generated by Django 4.1.2 on 2022-11-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogmodel_file_upload_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='blog/uploads/file_upload'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/uploads/image'),
        ),
    ]
